version: '2.1'
services:
  app:
    build: .
    links:
      - elasticsearch
    depends_on:
      elasticsearch:
        condition: service_healthy
    network_mode: bridge
    restart: on-failure

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.2
    container_name: elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    network_mode: bridge
    healthcheck:
      test: ["CMD", "curl", "http://localhost:9200/_nodes?pretty=true"]
      interval: 30s
      timeout: 10s
      retries: 5

  kibana:
    image: docker.elastic.co/kibana/kibana:6.6.2
    container_name: kibana
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_URL: http://elasticsearch:9200/
    ports:
      - "5601:5601"
    links:
      - elasticsearch
    depends_on:
      elasticsearch:
        condition: service_healthy
    network_mode: bridge

  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ${PWD}/nginx-config/:/etc/nginx/conf.d/
    command: /bin/bash -c "nginx -g 'daemon off;'"
    ulimits:
      nproc: 65535
